import { Category, Brand, Product, ProductDetail } from '@/types';

export const DEMO_CATEGORIES: Category[] = [
  { id: 1, name: 'Youth Apparel', slug: 'youth', icon: 'Shirt', description: 'T-Shirts, Hoodies, Shorts & Sweats for Youth' },
  { id: 2, name: 'Adult Apparel', slug: 'adults', icon: 'User', description: 'Official MrBeast Merch for Adults' },
  { id: 3, name: 'Football Collection', slug: 'beast-athletics-football', icon: 'Trophy', description: 'Brand New Beast Athletics Football Drop' },
  { id: 4, name: 'Sports & Fitness', slug: 'beast-athletics', icon: 'Activity', description: 'Jerseys, Shorts, Footballs & Gear' },
  { id: 5, name: 'Feastables', slug: 'feastables', icon: 'Candy', description: 'MrBeast Chocolate, Gummies & Peanut Butter Cups' },
  { id: 6, name: 'Toys & Tech', slug: 'mrbeast-lab', icon: 'Gamepad2', description: 'MrBeast Lab Mega-Tech Mutators & Figures' },
  { id: 7, name: 'Halloween Shop', slug: 'halloween-shop', icon: 'Ghost', description: 'Limited Edition Spooky Drops & Bundles' },
  { id: 8, name: 'School & Office', slug: 'school-office', icon: 'Backpack', description: 'Glow in the dark backpacks, socks & essentials' },
];

export const DEMO_BRANDS: Brand[] = [
  { id: 1, name: 'MrBeast Official', slug: 'mrbeast', description: 'The ONLY Official Merch Store for MrBeast in the world' },
  { id: 2, name: 'Beast Athletics', slug: 'beast-athletics', description: 'High Performance Athletic Apparel & Gear' },
  { id: 3, name: 'Feastables', slug: 'feastables', description: 'Better for you chocolate and snacks by MrBeast' },
  { id: 4, name: 'MrBeast Lab', slug: 'mrbeast-lab', description: 'Mega-Tech Mutators and interactive figures' },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Beast Edition Plate Tee',
    slug: 'beast-edition-plate-tee',
    shortDescription: 'The Beast Edition Plate Tee showcases the panther head inside a vibrant home plate design with bold accents. Made from 100% cotton with a custom relaxed fit.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/BeastEditionPlateTee_Black.jpg?v=1773158368&width=800',
    warrantyMonths: 0,
    featured: true,
    minPrice: 24.49,
    originalPrice: 28.00,
    totalStock: 85,
    categoryName: 'Youth Apparel',
    categorySlug: 'youth',
    brandName: 'MrBeast Official',
    brandSlug: 'mrbeast',
  },
  {
    id: 2,
    name: 'MrBeast Clone Tee',
    slug: 'youth-clone-tee-black',
    shortDescription: 'High-energy Clone artwork front and back. 100% ultra-soft cotton, relaxed athletic cut and long-lasting direct-to-film graphic prints.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/B2S_CLONE_T_BACK.jpg?v=1783001446&width=800',
    warrantyMonths: 0,
    featured: true,
    minPrice: 24.49,
    originalPrice: 28.00,
    totalStock: 60,
    categoryName: 'Youth Apparel',
    categorySlug: 'youth',
    brandName: 'MrBeast Official',
    brandSlug: 'mrbeast',
  },
  {
    id: 3,
    name: 'Beast Athletics Flame Shorts',
    slug: 'beast-athletics-flame-shorts',
    shortDescription: 'Breathable sports mesh shorts featuring iconic cyan and pink flame gradient graphics, deep zip pockets, and Beast elastic waistband.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/BaseballFlameShorts_1.jpg?v=1773156477&width=800',
    warrantyMonths: 0,
    featured: true,
    minPrice: 34.29,
    originalPrice: 40.00,
    totalStock: 45,
    categoryName: 'Sports & Fitness',
    categorySlug: 'beast-athletics',
    brandName: 'Beast Athletics',
    brandSlug: 'beast-athletics',
  },
  {
    id: 4,
    name: 'MB Panther Baseball Shorts',
    slug: 'mb-panther-baseball-shorts',
    shortDescription: 'Heavyweight athletic mesh shorts with stitched panther logo, side split hem, and reinforced athletic drawstrings.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/MBPantherBaseballShorts_1.jpg?v=1774975613&width=800',
    warrantyMonths: 0,
    featured: true,
    minPrice: 34.29,
    originalPrice: 40.00,
    totalStock: 30,
    categoryName: 'Sports & Fitness',
    categorySlug: 'beast-athletics',
    brandName: 'Beast Athletics',
    brandSlug: 'beast-athletics',
  },
  {
    id: 5,
    name: 'Beast Noise Tee',
    slug: 'beast-noise-tee',
    shortDescription: 'Glitch noise distortion MrBeast panther graphics. Tagless collar for premium comfort, 100% pre-shrunk ring-spun cotton.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/B2S_NoiseTee_BLK_BACK.jpg?v=1785206597&width=800',
    warrantyMonths: 0,
    featured: true,
    minPrice: 24.49,
    originalPrice: 28.00,
    totalStock: 50,
    categoryName: 'Youth Apparel',
    categorySlug: 'youth',
    brandName: 'MrBeast Official',
    brandSlug: 'mrbeast',
  },
  {
    id: 6,
    name: 'Collegiate Beast Sweat Set Bundle - Blue',
    slug: 'collegiate-beast-sweat-set-bundle',
    shortDescription: 'Complete bundle including the Collegiate Beast Hoodie and matching Sweatpants in Carolina Blue. Premium fleece with brushed interior.',
    thumbnail: 'https://cdn.shopify.com/s/files/1/0016/1975/5059/files/CollegiateBeastSet_BLU_1.jpg?v=1790615344',
    warrantyMonths: 0,
    featured: true,
    minPrice: 74.95,
    originalPrice: 88.18,
    totalStock: 40,
    categoryName: 'Football Collection',
    categorySlug: 'beast-athletics-football',
    brandName: 'MrBeast Official',
    brandSlug: 'mrbeast',
  },
  {
    id: 7,
    name: 'Beast Football Jersey & Shorts Set',
    slug: 'beast-football-jersey-shorts-set',
    shortDescription: 'Game-ready Beast 2026 Jersey with Beast Bolt allover athletic shorts. Breathable moisture-wicking jersey with stitched number 12.',
    thumbnail: 'https://cdn.shopify.com/s/files/1/0016/1975/5059/files/StartingLineUpBundle_1.jpg?v=1790628847',
    warrantyMonths: 0,
    featured: true,
    minPrice: 74.95,
    originalPrice: 88.18,
    totalStock: 25,
    categoryName: 'Football Collection',
    categorySlug: 'beast-athletics-football',
    brandName: 'Beast Athletics',
    brandSlug: 'beast-athletics',
  },
  {
    id: 8,
    name: 'Beast 2 Pack Football Bundle',
    slug: 'beast-2-pack-football-bundle',
    shortDescription: 'Includes Cyan Blue and Neon Pink official regulation grip MrBeast footballs plus inflation pump and needles in collector box.',
    thumbnail: 'https://cdn.shopify.com/s/files/1/0016/1975/5059/files/FOOTBALL_PNK_BLU.jpg?v=1780066668',
    warrantyMonths: 0,
    featured: true,
    minPrice: 58.29,
    originalPrice: 68.58,
    totalStock: 70,
    categoryName: 'Football Collection',
    categorySlug: 'beast-athletics-football',
    brandName: 'Beast Athletics',
    brandSlug: 'beast-athletics',
  },
  {
    id: 9,
    name: 'Feastables Halloween King Size Chocolate Bundle',
    slug: 'feastables-halloween-king-size-bundle',
    shortDescription: 'Limited Edition Halloween Feastables bundle packed with Milk Chocolate and Milk Crunch king size bars made with grass-fed milk.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/Milkchocolate_10ct_MilkChocolate_10ct_f85cafd4-afe1-46e0-8dce-92d0206676bf.jpg?v=1790304667&width=800',
    warrantyMonths: 0,
    featured: true,
    minPrice: 58.78,
    originalPrice: 68.57,
    totalStock: 15,
    categoryName: 'Feastables',
    categorySlug: 'feastables',
    brandName: 'Feastables',
    brandSlug: 'feastables',
  },
  {
    id: 10,
    name: 'Halloween Peanut Butter Jack-O-Lantern Cups',
    slug: 'halloween-jack-o-lantern-cups-bundle',
    shortDescription: 'Rich creamy peanut butter encased in velvety milk chocolate shaped like spooky Jack-O-Lanterns. 100% natural ingredients.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/MB_HalloweenPDP_PBCup_7.jpg?v=1788468335&width=800',
    warrantyMonths: 0,
    featured: true,
    minPrice: 39.19,
    originalPrice: 48.98,
    totalStock: 100,
    categoryName: 'Feastables',
    categorySlug: 'feastables',
    brandName: 'Feastables',
    brandSlug: 'feastables',
  },
  {
    id: 11,
    name: 'Chocolate Variety Bulk Box (3lb Box)',
    slug: 'feastables-chocolate-variety-bulk-box',
    shortDescription: 'Massive 3lb assortment box featuring Milk Chocolate, Peanut Butter, Milk Crunch, and Dark Chocolate Sea Salt snack sizes.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/Chocolate_Variety_3lb_Box.png?v=1781029251&width=800',
    warrantyMonths: 0,
    featured: true,
    minPrice: 44.10,
    originalPrice: 48.99,
    totalStock: 80,
    categoryName: 'Feastables',
    categorySlug: 'feastables',
    brandName: 'Feastables',
    brandSlug: 'feastables',
  },
  {
    id: 12,
    name: 'Authentic Beast Edition Baseball Jersey',
    slug: 'authentic-beast-edition-baseball-jersey',
    shortDescription: 'Full button-front baseball jersey with tackle twill Beast lettering, contrast piping, and athletic mesh construction.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/AuthenticBaseballJersey_1_7004e04b-ef68-4145-9f44-9035d0839f47.jpg?v=1774975613&width=800',
    warrantyMonths: 0,
    featured: true,
    minPrice: 49.99,
    originalPrice: 59.99,
    totalStock: 35,
    categoryName: 'Sports & Fitness',
    categorySlug: 'beast-athletics',
    brandName: 'Beast Athletics',
    brandSlug: 'beast-athletics',
  },
  {
    id: 13,
    name: 'Beast Particle Tee - Adult',
    slug: 'beast-particle-ss-tee-black-adult',
    shortDescription: 'Signature Beast Panther disintegrating particle artwork. Premium combed cotton jersey cut for adults.',
    thumbnail: 'https://cdn.shopify.com/s/files/1/0016/1975/5059/files/Particle_Back_3831c086-bd01-459b-9ebf-5c9fa1876e66.jpg?v=1787232666',
    warrantyMonths: 0,
    featured: false,
    minPrice: 29.39,
    originalPrice: 34.00,
    totalStock: 95,
    categoryName: 'Adult Apparel',
    categorySlug: 'adults',
    brandName: 'MrBeast Official',
    brandSlug: 'mrbeast',
  },
  {
    id: 14,
    name: 'MrBeast x NARUTO Uzumaki Flash Tee - Adult',
    slug: 'mrbeast-x-naruto-uzumaki-flash-tee-adult',
    shortDescription: 'Official MrBeast x Naruto Shippuden collaboration tee featuring Naruto Uzumaki with beast mode lightning chakra.',
    thumbnail: 'https://cdn.shopify.com/s/files/1/0016/1975/5059/files/UZUMAKI_Tee_Flat_8e825fca-c1bc-4391-9391-b09276e71c3c.jpg?v=1787232667',
    warrantyMonths: 0,
    featured: false,
    minPrice: 34.29,
    originalPrice: 38.00,
    totalStock: 20,
    categoryName: 'Adult Apparel',
    categorySlug: 'adults',
    brandName: 'MrBeast Official',
    brandSlug: 'mrbeast',
  },
  {
    id: 15,
    name: 'Glow in the Dark Back to School Set',
    slug: 'glow-in-the-dark-back-to-school-set',
    shortDescription: 'Ultimate school set: Glow-in-the-dark backpack, luminous socks, neon shoelaces, and vinyl sticker pack.',
    thumbnail: 'https://cdn.shopify.com/s/files/1/0016/1975/5059/files/B2S_Bundle11.jpg?v=1785174985',
    warrantyMonths: 0,
    featured: false,
    minPrice: 66.63,
    originalPrice: 78.36,
    totalStock: 42,
    categoryName: 'School & Office',
    categorySlug: 'school-office',
    brandName: 'MrBeast Official',
    brandSlug: 'mrbeast',
  },
  {
    id: 16,
    name: 'The Most Dangerous Games Book',
    slug: 'the-most-dangerous-games-book',
    shortDescription: 'The Book Event of the Year! Enter the competition for your chance at $1,000,000. Contains exclusive puzzles and entry code inside.',
    thumbnail: 'https://mrbeast.store/cdn/shop/files/BookImage-HP-Desktop.png?v=1788880566&width=1000',
    warrantyMonths: 0,
    featured: false,
    minPrice: 19.99,
    originalPrice: 24.99,
    totalStock: 500,
    categoryName: 'Toys & Tech',
    categorySlug: 'mrbeast-lab',
    brandName: 'MrBeast Official',
    brandSlug: 'mrbeast',
  },
];

export const DEMO_PRODUCT_DETAILS: Record<string, ProductDetail> = {
  'beast-edition-plate-tee': {
    ...DEMO_PRODUCTS[0],
    detailDescription: 'The Beast Edition Plate Tee showcases the panther head inside a vibrant home plate design with bold accents. Made from 100% cotton with a custom relaxed fit, and soft-touch finish, this tee makes a statement on and off the field. Grab it in Black, Heather Gray, or White and bring that Beast energy everywhere you go.',
    specifications: JSON.stringify({
      Material: '100% Ring-Spun Cotton',
      Fit: 'Custom Relaxed Athletic Fit',
      Print: 'Front & Back High Density Direct-To-Film',
      Collar: 'Tagless comfort band',
      Care: 'Machine wash cold inside out, tumble dry low',
      Origin: 'Designed in North Carolina, USA',
    }),
    variants: [
      { id: 101, sku: 'MB-PLATE-BLK-YS', variantName: 'Black / Small (6-7)', price: 24.49, originalPrice: 28.00, stockQuantity: 20, active: true },
      { id: 102, sku: 'MB-PLATE-BLK-YM', variantName: 'Black / Medium (8-9)', price: 24.49, originalPrice: 28.00, stockQuantity: 25, active: true },
      { id: 103, sku: 'MB-PLATE-BLK-YL', variantName: 'Black / Large (10-11)', price: 24.49, originalPrice: 28.00, stockQuantity: 30, active: true },
      { id: 104, sku: 'MB-PLATE-BLK-YXL', variantName: 'Black / XL (12-13)', price: 24.49, originalPrice: 28.00, stockQuantity: 10, active: true },
      { id: 105, sku: 'MB-PLATE-WHT-YM', variantName: 'White / Medium (8-9)', price: 24.49, originalPrice: 28.00, stockQuantity: 15, active: true },
      { id: 106, sku: 'MB-PLATE-GRY-YL', variantName: 'Heather Gray / Large (10-11)', price: 24.49, originalPrice: 28.00, stockQuantity: 18, active: true },
    ],
  },
  'collegiate-beast-sweat-set-bundle': {
    ...DEMO_PRODUCTS[5],
    detailDescription: 'Gear up for the season with the official Collegiate Beast Sweat Set Bundle. Features the heavy-blend pullover hoodie with kangaroo pocket and collegiate Beast arch embroidery, paired with cuffed sweatpants with elastic drawstring waist and deep side pockets.',
    specifications: JSON.stringify({
      Fabric: '80% Cotton / 20% Polyester Heavy Fleece',
      Embroidery: 'Raised Beast Athletic Arch Stitched Logo',
      Pants: 'Elastic Waistband with Metal Tipped Drawstring',
      Warmth: 'Extra soft brushed interior lining',
      Care: 'Machine wash cold, hang dry recommended',
    }),
    variants: [
      { id: 201, sku: 'MB-COLL-BLU-S', variantName: 'Carolina Blue / Small (6-7)', price: 74.95, originalPrice: 88.18, stockQuantity: 10, active: true },
      { id: 202, sku: 'MB-COLL-BLU-M', variantName: 'Carolina Blue / Medium (8-9)', price: 74.95, originalPrice: 88.18, stockQuantity: 15, active: true },
      { id: 203, sku: 'MB-COLL-BLU-L', variantName: 'Carolina Blue / Large (10-11)', price: 74.95, originalPrice: 88.18, stockQuantity: 12, active: true },
      { id: 204, sku: 'MB-COLL-BLU-XL', variantName: 'Carolina Blue / XL (12-13)', price: 74.95, originalPrice: 88.18, stockQuantity: 8, active: true },
    ],
  },
  'beast-athletics-flame-shorts': {
    ...DEMO_PRODUCTS[2],
    detailDescription: 'Dominate the field or the street in the Beast Athletics Flame Shorts. Engineered from double-layer athletic mesh for optimal airflow, featuring the iconic cyan-to-pink gradient flame graphics that turn heads.',
    specifications: JSON.stringify({
      Material: '100% Breathable Athletic Poly Mesh',
      Inseam: '6 inch athletic cut above the knee',
      Pockets: 'Two deep zippered side hand pockets',
      Waist: 'Ribbed knit waistband with internal drawcord',
    }),
    variants: [
      { id: 301, sku: 'MB-FLAME-S', variantName: 'Small', price: 34.29, originalPrice: 40.00, stockQuantity: 12, active: true },
      { id: 302, sku: 'MB-FLAME-M', variantName: 'Medium', price: 34.29, originalPrice: 40.00, stockQuantity: 18, active: true },
      { id: 303, sku: 'MB-FLAME-L', variantName: 'Large', price: 34.29, originalPrice: 40.00, stockQuantity: 20, active: true },
      { id: 304, sku: 'MB-FLAME-XL', variantName: 'XL', price: 34.29, originalPrice: 40.00, stockQuantity: 15, active: true },
    ],
  },
  'beast-football-jersey-shorts-set': {
    ...DEMO_PRODUCTS[6],
    detailDescription: 'The official starting lineup football set. Comes with the Beast 2026 game jersey featuring sewn number 12, breathable perforated mesh sleeves, and the Beast Bolt allover athletic shorts.',
    specifications: JSON.stringify({
      Jersey: '100% Recycled Polyester Mesh with UV Protection',
      Numbers: 'Tackle Twill Stitched Number 12 & BEAST nameplate',
      Shorts: 'Moisture-wicking 4-way stretch shorts with liner',
    }),
    variants: [
      { id: 401, sku: 'MB-FBSET-S', variantName: 'Youth Small (6-7)', price: 74.95, originalPrice: 88.18, stockQuantity: 8, active: true },
      { id: 402, sku: 'MB-FBSET-M', variantName: 'Youth Medium (8-9)', price: 74.95, originalPrice: 88.18, stockQuantity: 12, active: true },
      { id: 403, sku: 'MB-FBSET-L', variantName: 'Youth Large (10-11)', price: 74.95, originalPrice: 88.18, stockQuantity: 10, active: true },
    ],
  },
};
