import { Category, Brand, Product, ProductDetail } from '@/types';

export const DEMO_CATEGORIES: Category[] = [
  { id: 1, name: 'Laptops & MacBooks', slug: 'laptops', icon: 'Laptop', description: 'Apple MacBook Pro M3, ASUS ROG Zephyrus, Razer Blade & Workstations' },
  { id: 2, name: 'Custom Gaming PCs', slug: 'gaming-pc', icon: 'Cpu', description: 'Liquid-cooled RTX 4090 battlestations and pro creator rigs' },
  { id: 3, name: 'Màn Hình Gaming & OLED', slug: 'monitors', icon: 'Monitor', description: '4K QD-OLED, UltraWide 240Hz, và màn hình đồ họa chuyên nghiệp' },
  { id: 4, name: 'Bàn Phím Cơ Custom', slug: 'keyboards', icon: 'Keyboard', description: 'Bàn phím cơ nhôm CNC, Rapid Trigger quang học & keycaps cao cấp' },
  { id: 5, name: 'Chuột Gaming & Gears', slug: 'mice', icon: 'Mouse', description: 'Chuột siêu nhẹ 4K/8K polling rate, mousepad và phụ kiện esports' },
  { id: 6, name: 'Tai Nghe & Hi-End Audio', slug: 'audio', icon: 'Headphones', description: 'Tai nghe chống ồn ANC, tai nghe kiểm âm audiophile & DAC/Amp' },
  { id: 7, name: 'Linh Kiện Máy Tính', slug: 'components', icon: 'HardDrive', description: 'Card đồ họa NVIDIA RTX 4090, CPU Intel i9/Ryzen 9 & RAM DDR5' },
  { id: 8, name: 'Điện Thoại & Handhelds', slug: 'smartphones', icon: 'Smartphone', description: 'Flagship smartphones, Steam Deck OLED & thiết bị cầm tay' },
];

export const DEMO_BRANDS: Brand[] = [
  { id: 1, name: 'Apple', slug: 'apple', description: 'MacBook Pro, iPhone 16 Pro Max, iPad Pro và hệ sinh thái Apple Silicon' },
  { id: 2, name: 'ASUS ROG', slug: 'asus-rog', description: 'Republic of Gamers - Zephyrus, Strix, Maximus và màn hình OLED gaming đỉnh cao' },
  { id: 3, name: 'NVIDIA', slug: 'nvidia', description: 'GeForce RTX 40 Series, DLSS 3.5 và nền tảng đồ họa Ray Tracing tối thượng' },
  { id: 4, name: 'Sony', slug: 'sony', description: 'Công nghệ âm thanh hàng đầu thế giới với dòng tai nghe WH-1000XM5 ANC' },
  { id: 5, name: 'Razer', slug: 'razer', description: 'Thương hiệu gaming hàng đầu thế giới - For Gamers, By Gamers' },
  { id: 6, name: 'Logitech G', slug: 'logitech-g', description: 'Chuột siêu nhẹ PRO X Superlight và phụ kiện thi đấu esports đỉnh cao' },
  { id: 7, name: 'Corsair', slug: 'corsair', description: 'Bộ nhớ RAM Dominator Titanium, tản nhiệt nước và linh kiện PC cao cấp' },
  { id: 8, name: 'Keychron', slug: 'keychron', description: 'Bàn phím cơ full nhôm CNC không dây chuyên nghiệp cho Mac và Windows' },
  { id: 9, name: 'Samsung', slug: 'samsung', description: 'Màn hình Odyssey OLED cong siêu rộng và siêu phẩm công nghệ hiển thị' },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Apple MacBook Pro 16" (M3 Max, 36GB RAM, 1TB SSD, Space Black)',
    slug: 'macbook-pro-16-m3-max',
    shortDescription: 'Cỗ máy đồ họa tối thượng trang bị chip Apple M3 Max 16-core CPU, 40-core GPU, màn hình Liquid Retina XDR 120Hz ProMotion và màu Space Black đẳng cấp.',
    thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 12,
    featured: true,
    minPrice: 3499.00,
    originalPrice: 3799.00,
    totalStock: 35,
    categoryName: 'Laptops & MacBooks',
    categorySlug: 'laptops',
    brandName: 'Apple',
    brandSlug: 'apple',
  },
  {
    id: 2,
    name: 'ASUS ROG Zephyrus G16 OLED (Intel Core Ultra 9, RTX 4090, 32GB RAM)',
    slug: 'asus-rog-zephyrus-g16-oled',
    shortDescription: 'Laptop gaming mỏng nhẹ cao cấp nhất trang bị màn hình ROG Nebula OLED 240Hz, card đồ họa NVIDIA RTX 4090 16GB VRAM, khung nhôm CNC nguyên khối.',
    thumbnail: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 24,
    featured: true,
    minPrice: 2899.99,
    originalPrice: 3199.99,
    totalStock: 20,
    categoryName: 'Laptops & MacBooks',
    categorySlug: 'laptops',
    brandName: 'ASUS ROG',
    brandSlug: 'asus-rog',
  },
  {
    id: 3,
    name: 'TITAN BEAST RTX 4090 Custom Watercooled Gaming PC Rig',
    slug: 'titan-beast-rtx-4090-custom-rig',
    shortDescription: 'Cỗ máy chiến game & render đỉnh cao: Core i9-14900KS, NVIDIA GeForce RTX 4090 24GB, 64GB DDR5 RGB 6600MHz, tản nhiệt nước Custom Hardline kép.',
    thumbnail: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 36,
    featured: true,
    minPrice: 4299.00,
    originalPrice: 4699.00,
    totalStock: 12,
    categoryName: 'Custom Gaming PCs',
    categorySlug: 'gaming-pc',
    brandName: 'NVIDIA',
    brandSlug: 'nvidia',
  },
  {
    id: 4,
    name: 'CYBERPUNK ROG Hyperion Custom Hardline Battlestation',
    slug: 'cyberpunk-rog-hyperion-custom-rig',
    shortDescription: 'Siêu phẩm case ROG Hyperion GR701 trang bị full linh kiện ASUS ROG Strix, RTX 4090 OC, bo mạch chủ ROG Maximus Z790 Dark Hero và nguồn Thor 1200W.',
    thumbnail: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 36,
    featured: true,
    minPrice: 4999.00,
    originalPrice: 5499.00,
    totalStock: 8,
    categoryName: 'Custom Gaming PCs',
    categorySlug: 'gaming-pc',
    brandName: 'ASUS ROG',
    brandSlug: 'asus-rog',
  },
  {
    id: 5,
    name: 'Samsung Odyssey OLED G9 49" Curved Dual QHD 240Hz Monitor',
    slug: 'samsung-odyssey-oled-g9-49',
    shortDescription: 'Màn hình OLED cong 49 inch tỷ lệ 32:9 siêu rộng, độ phân giải Dual QHD (5120x1440), tần số quét 240Hz thời gian phản hồi 0.03ms tốc độ thần sầu.',
    thumbnail: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 36,
    featured: true,
    minPrice: 1499.99,
    originalPrice: 1799.99,
    totalStock: 25,
    categoryName: 'Màn Hình Gaming & OLED',
    categorySlug: 'monitors',
    brandName: 'Samsung',
    brandSlug: 'samsung',
  },
  {
    id: 6,
    name: 'ASUS ROG Swift PG32UCDM 32" 4K QD-OLED 240Hz Pro Gaming Monitor',
    slug: 'asus-rog-swift-pg32ucdm-4k-oled',
    shortDescription: 'Màn hình thế hệ mới 32 inch 4K QD-OLED độ chuẩn màu 99% DCI-P3, tần số quét 240Hz siêu mượt, tản nhiệt graphene cao cấp chống burn-in tuyệt đối.',
    thumbnail: 'https://images.unsplash.com/photo-1547119957-637f8679db1e?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 36,
    featured: true,
    minPrice: 1299.00,
    originalPrice: 1399.00,
    totalStock: 18,
    categoryName: 'Màn Hình Gaming & OLED',
    categorySlug: 'monitors',
    brandName: 'ASUS ROG',
    brandSlug: 'asus-rog',
  },
  {
    id: 7,
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard (Full CNC Aluminum)',
    slug: 'keychron-q1-pro-wireless-custom-keyboard',
    shortDescription: 'Bàn phím cơ custom vỏ nhôm CNC nguyên khối, kết nối Bluetooth 5.1 & Type-C, núm xoay Knob đa năng, hỗ trợ QMK/VIA keymap và switch hotswap.',
    thumbnail: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 12,
    featured: true,
    minPrice: 199.99,
    originalPrice: 229.99,
    totalStock: 65,
    categoryName: 'Bàn Phím Cơ Custom',
    categorySlug: 'keyboards',
    brandName: 'Keychron',
    brandSlug: 'keychron',
  },
  {
    id: 8,
    name: 'Razer Huntsman V3 Pro Analog Optical Esports Keyboard',
    slug: 'razer-huntsman-v3-pro-analog-keyboard',
    shortDescription: 'Vũ khí esports chuyên nghiệp với Switch quang học analog Gen-2 điều chỉnh điểm kích hoạt 0.1-4.0mm, tính năng Rapid Trigger phản xạ cực nhanh.',
    thumbnail: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 24,
    featured: true,
    minPrice: 249.99,
    originalPrice: 279.99,
    totalStock: 40,
    categoryName: 'Bàn Phím Cơ Custom',
    categorySlug: 'keyboards',
    brandName: 'Razer',
    brandSlug: 'razer',
  },
  {
    id: 9,
    name: 'Logitech G PRO X Superlight 2 Wireless Gaming Mouse (60g)',
    slug: 'logitech-g-pro-x-superlight-2',
    shortDescription: 'Huyền thoại chuột gaming thi đấu siêu nhẹ 60g, cảm biến HERO 2 32.000 DPI, switch quang học cơ lai LIGHTFORCE và tần số gửi tín hiệu không dây 4K Polling.',
    thumbnail: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 24,
    featured: true,
    minPrice: 159.99,
    originalPrice: 179.99,
    totalStock: 80,
    categoryName: 'Chuột Gaming & Gears',
    categorySlug: 'mice',
    brandName: 'Logitech G',
    brandSlug: 'logitech-g',
  },
  {
    id: 10,
    name: 'Razer Viper V3 Pro Ultra-Lightweight Wireless Gaming Mouse (54g)',
    slug: 'razer-viper-v3-pro-wireless',
    shortDescription: 'Chuột esports nhẹ nhất phân khúc chỉ 54g, công nghệ không dây 8000Hz HyperPolling siêu tốc, cảm biến quang học Focus Pro 35K Gen-2 độ chuẩn xác 99.8%.',
    thumbnail: 'https://images.unsplash.com/photo-1626218174358-7769486c4b79?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 24,
    featured: true,
    minPrice: 159.99,
    originalPrice: 169.99,
    totalStock: 55,
    categoryName: 'Chuột Gaming & Gears',
    categorySlug: 'mice',
    brandName: 'Razer',
    brandSlug: 'razer',
  },
  {
    id: 11,
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Flagship Headphones',
    slug: 'sony-wh-1000xm5-wireless-anc-headphones',
    shortDescription: 'Tai nghe chụp tai chống ồn chủ động tốt nhất hiện nay, trang bị 2 bộ xử lý âm thanh V1 & QN1, màng loa carbon 30mm và chuẩn truyền tải LDAC Hi-Res Audio.',
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 12,
    featured: true,
    minPrice: 399.99,
    originalPrice: 449.99,
    totalStock: 48,
    categoryName: 'Tai Nghe & Hi-End Audio',
    categorySlug: 'audio',
    brandName: 'Sony',
    brandSlug: 'sony',
  },
  {
    id: 12,
    name: 'Sennheiser HD 660S2 Open-Back Audiophile Studio Headphones',
    slug: 'sennheiser-hd-660s2-audiophile-headphones',
    shortDescription: 'Tuyệt tác âm thanh phòng thu dạng mở (Open-back), trở kháng 300 Ohm tái tạo dải trầm siêu sâu và trường âm khoáng đạt cho giới audiophile sành điệu.',
    thumbnail: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 24,
    featured: true,
    minPrice: 499.95,
    originalPrice: 599.95,
    totalStock: 22,
    categoryName: 'Tai Nghe & Hi-End Audio',
    categorySlug: 'audio',
    brandName: 'Sony',
    brandSlug: 'sony',
  },
  {
    id: 13,
    name: 'NVIDIA GeForce RTX 4090 Founders Edition 24GB GDDR6X',
    slug: 'nvidia-geforce-rtx-4090-founders-edition',
    shortDescription: 'Card màn hình mạnh nhất hành tinh với kiến trúc Ada Lovelace, 16.384 nhân CUDA, 24GB GDDR6X 384-bit, xử lý đồ họa AI và 4K Gaming mượt mà không giới hạn.',
    thumbnail: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 36,
    featured: false,
    minPrice: 1699.99,
    originalPrice: 1799.99,
    totalStock: 15,
    categoryName: 'Linh Kiện Máy Tính',
    categorySlug: 'components',
    brandName: 'NVIDIA',
    brandSlug: 'nvidia',
  },
  {
    id: 14,
    name: 'Corsair Dominator Titanium RGB 64GB (2x32GB) DDR5 6600MHz CL32',
    slug: 'corsair-dominator-titanium-rgb-64gb-ddr5',
    shortDescription: 'Bộ kit RAM DDR5 cao cấp nhất của Corsair với thanh tản nhiệt nhôm rèn tinh xảo, 11 bóng LED RGB độc lập, hỗ trợ Intel XMP 3.0 ép xung ổn định tuyệt đối.',
    thumbnail: 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 60,
    featured: false,
    minPrice: 299.99,
    originalPrice: 349.99,
    totalStock: 50,
    categoryName: 'Linh Kiện Máy Tính',
    categorySlug: 'components',
    brandName: 'Corsair',
    brandSlug: 'corsair',
  },
  {
    id: 15,
    name: 'Apple iPhone 16 Pro Max 1TB (Titan Sa Mạc / Natural Titanium)',
    slug: 'apple-iphone-16-pro-max',
    shortDescription: 'Flagship di động tối tân nhất với khung viền Titanium siêu bền, chip Apple A18 Pro 3nm, hệ thống camera 48MP zoom quang 5x và hỗ trợ Apple Intelligence.',
    thumbnail: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 12,
    featured: false,
    minPrice: 1599.00,
    originalPrice: 1699.00,
    totalStock: 40,
    categoryName: 'Điện Thoại & Handhelds',
    categorySlug: 'smartphones',
    brandName: 'Apple',
    brandSlug: 'apple',
  },
  {
    id: 16,
    name: 'Valve Steam Deck OLED 1TB Handheld Gaming Console',
    slug: 'steam-deck-oled-1tb-handheld',
    shortDescription: 'Máy chơi game cầm tay màn hình HDR OLED 7.4 inch 90Hz rực rỡ, pin dung lượng lớn 50Wh, bộ nhớ 1TB NVMe SSD tốc độ cao và kính cường lực khắc chống lóa.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1000&auto=format&fit=crop&q=80',
    warrantyMonths: 12,
    featured: false,
    minPrice: 649.00,
    originalPrice: 699.00,
    totalStock: 30,
    categoryName: 'Điện Thoại & Handhelds',
    categorySlug: 'smartphones',
    brandName: 'Sony',
    brandSlug: 'sony',
  },
];

export const DEMO_PRODUCT_DETAILS: Record<string, ProductDetail> = {
  'macbook-pro-16-m3-max': {
    ...DEMO_PRODUCTS[0],
    detailDescription: 'MacBook Pro 16 inch với chip Apple M3 Max nâng tầm hiệu năng chuyên nghiệp lên một đỉnh cao mới. Với vi kiến trúc GPU mang tính cách mạng hỗ trợ Dynamic Caching, công nghệ dò tia Ray Tracing bằng phần cứng và thời lượng pin kỷ lục lên đến 22 giờ liên tục. Màn hình Liquid Retina XDR mang lại dải tần nhạy sáng vượt trội với độ sáng duy trì 1.000 nit và độ sáng tối đa 1.600 nit cho nội dung HDR.',
    specifications: JSON.stringify({
      'Vi xử lý': 'Apple M3 Max (16-core CPU, 40-core GPU, 16-core Neural Engine)',
      'Bộ nhớ RAM': '36GB Unified Memory (Băng thông 300GB/s)',
      'Ổ cứng': '1TB PCIe 4.0 SSD (Tốc độ đọc/ghi lên đến 7400MB/s)',
      'Màn hình': '16.2 inch Liquid Retina XDR (3456 x 2234), 120Hz ProMotion, 1600 nits HDR',
      'Cổng kết nối': '3x Thunderbolt 4 (USB-C), HDMI 2.1, Khe thẻ nhớ SDXC, MagSafe 3, Jack 3.5mm',
      'Trọng lượng': '2.16 kg (Màu Space Black chống bám vân tay)',
      'Hệ điều hành': 'macOS Sonoma (Tương thích hoàn hảo Apple Intelligence)',
    }),
    variants: [
      { id: 101, sku: 'MBP16-M3MAX-36-1TB-BLK', variantName: '36GB RAM / 1TB SSD / Space Black', price: 3499.00, originalPrice: 3799.00, stockQuantity: 15, active: true },
      { id: 102, sku: 'MBP16-M3MAX-48-1TB-BLK', variantName: '48GB RAM / 1TB SSD / Space Black', price: 3999.00, originalPrice: 4299.00, stockQuantity: 10, active: true },
      { id: 103, sku: 'MBP16-M3MAX-64-2TB-BLK', variantName: '64GB RAM / 2TB SSD / Space Black', price: 4499.00, originalPrice: 4799.00, stockQuantity: 6, active: true },
      { id: 104, sku: 'MBP16-M3MAX-128-4TB-SLV', variantName: '128GB RAM / 4TB SSD / Silver', price: 5499.00, originalPrice: 5999.00, stockQuantity: 4, active: true },
    ],
  },
  'asus-rog-zephyrus-g16-oled': {
    ...DEMO_PRODUCTS[1],
    detailDescription: 'ASUS ROG Zephyrus G16 định nghĩa lại chuẩn mực laptop gaming cao cấp. Khung nhôm CNC nguyên khối siêu mỏng chỉ 1.49cm, trang bị dải đèn Slash Lighting độc đáo trên nắp máy. Sức mạnh đến từ vi xử lý Intel Core Ultra 9 tích hợp NPU AI và card đồ họa NVIDIA GeForce RTX 4090 mang lại trải nghiệm chiến game AAA max settings và render 3D nhanh như chớp.',
    specifications: JSON.stringify({
      'Vi xử lý': 'Intel Core Ultra 9 185H (16 nhân, 22 luồng, Turbo 5.1GHz, AI Boost)',
      'Card đồ họa': 'NVIDIA GeForce RTX 4090 16GB GDDR6 (TGP 115W + Dynamic Boost)',
      'Bộ nhớ RAM': '32GB LPDDR5X 7467MHz Dual Channel',
      'Ổ cứng': '2TB M.2 NVMe PCIe 4.0 SSD',
      'Màn hình': '16.0" 2.5K (2560 x 1600) ROG Nebula OLED 240Hz, 0.2ms, G-Sync, 100% DCI-P3',
      'Hệ thống tản nhiệt': 'ROG Intelligent Cooling, Buồng hơi Vapor Chamber & Keo tản nhiệt kim loại lỏng',
      'Trọng lượng': '1.85 kg',
    }),
    variants: [
      { id: 201, sku: 'ROG-G16-4090-GRY', variantName: 'Eclipse Gray / RTX 4090 / 32GB / 2TB', price: 2899.99, originalPrice: 3199.99, stockQuantity: 10, active: true },
      { id: 202, sku: 'ROG-G16-4090-WHT', variantName: 'Platinum White / RTX 4090 / 32GB / 2TB', price: 2949.99, originalPrice: 3249.99, stockQuantity: 6, active: true },
      { id: 203, sku: 'ROG-G16-4080-GRY', variantName: 'Eclipse Gray / RTX 4080 / 32GB / 1TB', price: 2499.99, originalPrice: 2799.99, stockQuantity: 4, active: true },
    ],
  },
  'titan-beast-rtx-4090-custom-rig': {
    ...DEMO_PRODUCTS[2],
    detailDescription: 'TITAN BEAST RTX 4090 Custom Watercooled Gaming PC là siêu phẩm máy trạm chiến game được lắp ráp thủ công với tiêu chuẩn khắt khe nhất. Tản nhiệt nước Custom Hardline kép làm mát độc lập cho cả CPU Intel Core i9-14900KS và GPU RTX 4090 24GB, duy trì nhiệt độ dưới 55°C ngay cả trong điều kiện tải nặng liên tục nhiều giờ liền.',
    specifications: JSON.stringify({
      'CPU': 'Intel Core i9-14900KS (24 Cores, 32 Threads, Turbo 6.2GHz Special Edition)',
      'GPU': 'NVIDIA GeForce RTX 4090 Founders Edition 24GB GDDR6X Waterblock',
      'Mainboard': 'ASUS ROG MAXIMUS Z790 DARK HERO (Wi-Fi 7, PCIe 5.0)',
      'RAM': '64GB (2x32GB) Corsair Dominator Titanium DDR5 6600MHz CL32',
      'SSD': '2TB Samsung 990 PRO Gen4 NVMe (Tốc độ đọc 7450 MB/s)',
      'Tản nhiệt': 'Custom Hardline EKWB Liquid Cooling Dual 360mm Radiator',
      'Nguồn': 'Corsair AX1600i 1600W Titanium Full Modular',
      'Vỏ case': 'Lian Li O11 Dynamic EVO RGB Black Edition',
    }),
    variants: [
      { id: 301, sku: 'TITAN-RIG-14900KS-4090', variantName: 'Core i9-14900KS / RTX 4090 / 64GB DDR5 / 2TB NVMe', price: 4299.00, originalPrice: 4699.00, stockQuantity: 8, active: true },
      { id: 302, sku: 'TITAN-RIG-7950X3D-4090', variantName: 'AMD Ryzen 9 7950X3D / RTX 4090 / 64GB DDR5 / 4TB NVMe', price: 4499.00, originalPrice: 4899.00, stockQuantity: 4, active: true },
    ],
  },
  'samsung-odyssey-oled-g9-49': {
    ...DEMO_PRODUCTS[4],
    detailDescription: 'Đắm chìm hoàn toàn vào thế giới đồ họa với Samsung Odyssey OLED G9 49 inch. Sở hữu tỷ lệ 32:9 tương đương hai màn hình QHD 27 inch đặt cạnh nhau, độ cong 1800R bao trọn tầm nhìn ngoại vi. Tấm nền OLED thế hệ mới mang lại màu đen tuyệt đối, độ tương phản vô cực và tần số quét 240Hz thời gian đáp ứng 0.03ms (GtG) cho trải nghiệm mượt mà không đối thủ.',
    specifications: JSON.stringify({
      'Kích thước': '49 inch cong 1800R (Tỷ lệ siêu rộng 32:9)',
      'Độ phân giải': 'Dual QHD (5120 x 1440 pixels)',
      'Tấm nền': 'OLED với vi xử lý Neo Quantum Processor Pro',
      'Tần số quét': '240Hz, Thời gian phản hồi 0.03ms (GtG)',
      'Công nghệ đồng bộ': 'AMD FreeSync Premium Pro, VESA AdaptiveSync',
      'Độ sáng & Màu sắc': 'Peak 1000 nits, VESA DisplayHDR True Black 400, 99.3% DCI-P3',
      'Cổng kết nối': '1x DisplayPort 1.4, 1x HDMI 2.1, 1x Micro HDMI 2.1, USB Hub',
    }),
    variants: [
      { id: 401, sku: 'SAM-G95SC-49-OLED', variantName: '49" Dual QHD 240Hz OLED (Model G95SC)', price: 1499.99, originalPrice: 1799.99, stockQuantity: 15, active: true },
      { id: 402, sku: 'SAM-G85SB-34-OLED', variantName: '34" UltraWide WQHD 175Hz OLED (Model G85SB)', price: 899.99, originalPrice: 1099.99, stockQuantity: 10, active: true },
    ],
  },
  'keychron-q1-pro-wireless-custom-keyboard': {
    ...DEMO_PRODUCTS[6],
    detailDescription: 'Keychron Q1 Pro là bàn phím cơ custom vỏ nhôm CNC không dây cao cấp hàng đầu. Thiết kế Double Gasket Mount với nhiều lớp foam tiêu âm cho âm gõ đầm ấm "thocky". Hỗ trợ kết nối không dây Bluetooth 5.1 kết nối tối đa 3 thiết bị và cổng Type-C có dây 1000Hz polling rate. Trang bị switch K Pro bôi trơn sẵn từ nhà máy và keycaps PBT Double-shot OSA profile bền bỉ theo năm tháng.',
    specifications: JSON.stringify({
      'Vỏ phím': 'Nhôm nguyên khối CNC 6063 gia công tỉ mỉ',
      'Layout': '75% (81 phím) có núm xoay Knob kim loại đa năng',
      'Switch': 'Keychron K Pro Red / Brown / Banana (Pre-lubed, Hotswap 5-pin)',
      'Cấu trúc': 'Double-Gasket Mount với đệm Silicone & EVA foam cách âm',
      'Kết nối': 'Bluetooth 5.1 & Type-C wired (Tương thích Mac & Windows)',
      'Pin': '4000mAh (Lên đến 300 giờ khi tắt đèn LED)',
      'Tùy biến phần mềm': 'Hỗ trợ QMK/VIA trực tiếp trên trình duyệt',
    }),
    variants: [
      { id: 501, sku: 'KC-Q1P-BLK-RED', variantName: 'Carbon Black / Red Switch (Linear)', price: 199.99, originalPrice: 229.99, stockQuantity: 25, active: true },
      { id: 502, sku: 'KC-Q1P-SLV-BRN', variantName: 'Silver Gray / Brown Switch (Tactile)', price: 199.99, originalPrice: 229.99, stockQuantity: 20, active: true },
      { id: 503, sku: 'KC-Q1P-WHT-BAN', variantName: 'Shell White / Banana Switch (Early Tactile)', price: 209.99, originalPrice: 239.99, stockQuantity: 20, active: true },
    ],
  },
  'sony-wh-1000xm5-wireless-anc-headphones': {
    ...DEMO_PRODUCTS[10],
    detailDescription: 'Sony WH-1000XM5 thiết lập tiêu chuẩn mới cho dòng tai nghe chống ồn chủ động không dây. Sử dụng công nghệ Auto NC Optimizer tự động tối ưu hóa khả năng chống ồn theo môi trường đeo và áp suất không khí. Tận hưởng chất âm thuần khiết chuẩn Hi-Res Audio Wireless thông qua codec LDAC cùng khả năng đàm thoại trong trẻo với 4 micro định dạng chùm sóng AI.',
    specifications: JSON.stringify({
      'Loại tai nghe': 'Over-ear Chống ồn chủ động (Active Noise Canceling)',
      'Màng loa': '30mm mạ sợi carbon tổng hợp đặc chế',
      'Bộ xử lý âm thanh': 'Kép: Integrated Processor V1 + HD Noise Cancelling Processor QN1',
      'Bộ giải mã âm thanh': 'LDAC, AAC, SBC (Hi-Res Audio & Hi-Res Wireless)',
      'Thời lượng pin': '30 giờ (bật ANC) / 40 giờ (tắt ANC), sạc nhanh 3 phút được 3 giờ',
      'Kết nối': 'Bluetooth 5.2 đa điểm kết nối cùng lúc 2 thiết bị',
      'Trọng lượng': '250g siêu êm ái với đệm da mềm Soft Fit Leather',
    }),
    variants: [
      { id: 601, sku: 'SONY-XM5-BLK', variantName: 'Midnight Black', price: 399.99, originalPrice: 449.99, stockQuantity: 20, active: true },
      { id: 602, sku: 'SONY-XM5-SLV', variantName: 'Platinum Silver', price: 399.99, originalPrice: 449.99, stockQuantity: 18, active: true },
      { id: 603, sku: 'SONY-XM5-PNK', variantName: 'Smoky Pink Edition', price: 419.99, originalPrice: 469.99, stockQuantity: 10, active: true },
    ],
  },
  'logitech-g-pro-x-superlight-2': {
    ...DEMO_PRODUCTS[8],
    detailDescription: 'Logitech G PRO X Superlight 2 là biểu tượng của làng chuột esports thế giới. Trọng lượng siêu nhẹ chỉ 60g kết hợp cùng switch quang cơ học lai LIGHTFORCE mang lại cảm giác nhấn giòn tan và tốc độ kích hoạt ánh sáng tức thì. Cảm biến HERO 2 thế hệ mới đạt tới 32.000 DPI và khả năng truyền tín hiệu không dây 4000Hz không độ trễ.',
    specifications: JSON.stringify({
      'Cảm biến': 'HERO 2 thế hệ mới (100 - 32.000 DPI, >500 IPS, >40G)',
      'Switch chuột': 'LIGHTFORCE Optical-Mechanical Hybrid Switch',
      'Tần số phản hồi': '4000Hz (0.25ms) không dây LIGHTSPEED',
      'Trọng lượng': 'Chỉ 60g (Không lỗ tổ ong, cấu trúc nguyên khối bền chắc)',
      'Thời lượng pin': 'Lên đến 95 giờ chuyển động liên tục',
      'Chân đế (Feat)': '100% PTFE không pha tạp chất cho cảm giác lướt êm ái',
    }),
    variants: [
      { id: 701, sku: 'LOGI-GPX2-BLK', variantName: 'Matte Black (4K Polling)', price: 159.99, originalPrice: 179.99, stockQuantity: 35, active: true },
      { id: 702, sku: 'LOGI-GPX2-WHT', variantName: 'Pure White (4K Polling)', price: 159.99, originalPrice: 179.99, stockQuantity: 30, active: true },
      { id: 703, sku: 'LOGI-GPX2-PNK', variantName: 'Magenta Pink (4K Polling)', price: 169.99, originalPrice: 189.99, stockQuantity: 15, active: true },
    ],
  },
  'nvidia-geforce-rtx-4090-founders-edition': {
    ...DEMO_PRODUCTS[12],
    detailDescription: 'NVIDIA GeForce RTX 4090 Founders Edition là đỉnh cao của đồ họa hiện đại. Được xây dựng trên kiến trúc NVIDIA Ada Lovelace cực kỳ hiệu quả, mang lại bước nhảy vọt về hiệu năng và đồ họa được hỗ trợ bởi trí tuệ nhân tạo AI. Trải nghiệm thế giới ảo sống động như thật với công nghệ Ray Tracing đầy đủ và độ trễ siêu thấp cùng NVIDIA Reflex.',
    specifications: JSON.stringify({
      'Nhân xử lý CUDA': '16.384 nhân',
      'Bộ nhớ VRAM': '24GB GDDR6X 384-bit',
      'Xung nhịp tăng cường': '2.52 GHz',
      'Công nghệ AI': 'DLSS 3.5 Frame Generation & Ray Reconstruction',
      'Cổng xuất hình': '1x HDMI 2.1a, 3x DisplayPort 1.4a',
      'Công suất nguồn khuyến nghị': '850W (Cổng nguồn 16-pin 12VHPWR)',
    }),
    variants: [
      { id: 801, sku: 'NV-RTX4090-FE', variantName: 'Founders Edition 24GB GDDR6X', price: 1699.99, originalPrice: 1799.99, stockQuantity: 10, active: true },
      { id: 802, sku: 'NV-RTX4090-HYBRID', variantName: 'Water-Cooled AIO 24GB Edition', price: 1999.99, originalPrice: 2199.99, stockQuantity: 5, active: true },
    ],
  },
};
