import { Category, Brand, Product, ProductDetail } from '@/types';

export const DEMO_CATEGORIES: Category[] = [
  { id: 1, name: 'Laptop & MacBook', slug: 'laptop', icon: 'Laptop', description: 'Gaming, MacBook M3, Ultrabook' },
  { id: 2, name: 'Điện thoại & Tablet', slug: 'dien-thoai', icon: 'Smartphone', description: 'iPhone 16, Samsung Galaxy S24' },
  { id: 3, name: 'Màn hình máy tính', slug: 'man-hinh', icon: 'Monitor', description: 'OLED, 2K/4K 240Hz' },
  { id: 4, name: 'Tai nghe & Âm thanh', slug: 'tai-nghe', icon: 'Headphones', description: 'Sony ANC, Hi-Res Audio' },
  { id: 5, name: 'Bàn phím & Chuột', slug: 'ban-phim-chuot', icon: 'Keyboard', description: 'Keychron Custom, Chuột Gaming' },
];

export const DEMO_BRANDS: Brand[] = [
  { id: 1, name: 'Apple', slug: 'apple', description: 'Apple Inc.' },
  { id: 2, name: 'ASUS ROG', slug: 'asus', description: 'Republic of Gamers' },
  { id: 3, name: 'Sony', slug: 'sony', description: 'Sony Electronics' },
  { id: 4, name: 'Samsung', slug: 'samsung', description: 'Samsung Electronics' },
  { id: 5, name: 'Keychron', slug: 'keychron', description: 'Keychron Custom Keyboards' },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'MacBook Pro 16 inch M3 Max',
    slug: 'macbook-pro-16-inch-m3-max',
    shortDescription: 'Apple M3 Max (16-Core CPU, 40-Core GPU), 36GB RAM, 1TB SSD NVMe, Màn hình Liquid Retina XDR 120Hz.',
    thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
    warrantyMonths: 12,
    featured: true,
    minPrice: 89990000,
    originalPrice: 94990000,
    totalStock: 23,
    categoryName: 'Laptop & MacBook',
    categorySlug: 'laptop',
    brandName: 'Apple',
    brandSlug: 'apple',
  },
  {
    id: 2,
    name: 'Laptop Gaming ASUS ROG Strix SCAR 18 (2024)',
    slug: 'asus-rog-strix-scar-18-2024',
    shortDescription: 'Intel Core i9-14900HX, RTX 4090 16GB, 32GB RAM DDR5, 2TB SSD, Màn hình 18 inch Mini LED 240Hz 2.5K.',
    thumbnail: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800',
    warrantyMonths: 24,
    featured: true,
    minPrice: 119990000,
    originalPrice: 125000000,
    totalStock: 10,
    categoryName: 'Laptop & MacBook',
    categorySlug: 'laptop',
    brandName: 'ASUS ROG',
    brandSlug: 'asus',
  },
  {
    id: 3,
    name: 'Điện thoại iPhone 16 Pro Max',
    slug: 'iphone-16-pro-max',
    shortDescription: 'Chip Apple A18 Pro, Màn hình 6.9 inch Super Retina XDR 120Hz, Khung Titan sa mạc, Camera 48MP Zoom 5x.',
    thumbnail: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800',
    warrantyMonths: 12,
    featured: true,
    minPrice: 34990000,
    originalPrice: 36990000,
    totalStock: 43,
    categoryName: 'Điện thoại & Tablet',
    categorySlug: 'dien-thoai',
    brandName: 'Apple',
    brandSlug: 'apple',
  },
  {
    id: 4,
    name: 'Samsung Galaxy S24 Ultra 5G',
    slug: 'samsung-galaxy-s24-ultra-5g',
    shortDescription: 'Snapdragon 8 Gen 3, Quyền năng Galaxy AI, Camera 200MP, Màn hình phẳng 6.8 inch 2600 nits, Kèm bút S-Pen.',
    thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800',
    warrantyMonths: 12,
    featured: true,
    minPrice: 29990000,
    originalPrice: 33990000,
    totalStock: 20,
    categoryName: 'Điện thoại & Tablet',
    categorySlug: 'dien-thoai',
    brandName: 'Samsung',
    brandSlug: 'samsung',
  },
  {
    id: 5,
    name: 'Tai nghe không dây chống ồn Sony WH-1000XM5',
    slug: 'tai-nghe-chong-on-sony-wh-1000xm5',
    shortDescription: 'Chống ồn đỉnh cao bộ đôi V1 + QN1, Âm thanh Hi-Res LDAC, Pin 30 giờ liên tục, Sạc nhanh 3 phút.',
    thumbnail: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800',
    warrantyMonths: 12,
    featured: true,
    minPrice: 7990000,
    originalPrice: 8990000,
    totalStock: 52,
    categoryName: 'Tai nghe & Âm thanh',
    categorySlug: 'tai-nghe',
    brandName: 'Sony',
    brandSlug: 'sony',
  },
  {
    id: 6,
    name: 'Bàn phím cơ không dây nhôm nguyên khối Keychron Q1 Pro',
    slug: 'ban-phim-co-keychron-q1-pro',
    shortDescription: 'Vỏ nhôm CNC 75% Anodized, Gasket Mount êm ái, Hotswap switch, Bluetooth 5.1 & Type-C, Tương thích Mac/Win.',
    thumbnail: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
    warrantyMonths: 12,
    featured: false,
    minPrice: 4690000,
    originalPrice: 4990000,
    totalStock: 16,
    categoryName: 'Bàn phím & Chuột',
    categorySlug: 'ban-phim-chuot',
    brandName: 'Keychron',
    brandSlug: 'keychron',
  },
];

export const DEMO_PRODUCT_DETAILS: Record<string, ProductDetail> = {
  'macbook-pro-16-inch-m3-max': {
    ...DEMO_PRODUCTS[0],
    detailDescription: 'MacBook Pro 16 inch với chip M3 Max đem lại tốc độ xử lý dựng phim 8K, render 3D và chạy mô hình học máy cực nhanh. Thời lượng pin kỷ lục lên tới 22 giờ liên tục.',
    specifications: JSON.stringify({
      CPU: 'Apple M3 Max (16-Core CPU, 40-Core GPU)',
      RAM: '36GB / 48GB / 64GB Unified Memory',
      'Ổ cứng': '1TB / 2TB SSD NVMe',
      'Màn hình': '16.2 inch Liquid Retina XDR (3456x2234), 120Hz ProMotion, 1600 nits',
      Pin: '100Wh, sạc nhanh 140W MagSafe 3',
      'Trọng lượng': '2.16 kg',
      'Cổng kết nối': '3x Thunderbolt 4 (USB-C), HDMI, SDXC card, Jack 3.5mm',
    }),
    variants: [
      {
        id: 101,
        sku: 'MBP16-M3MAX-36-1TB-BLACK',
        variantName: 'Đen Không Gian (Space Black) - 36GB RAM / 1TB SSD',
        price: 89990000,
        originalPrice: 94990000,
        stockQuantity: 15,
        active: true,
      },
      {
        id: 102,
        sku: 'MBP16-M3MAX-48-2TB-SILVER',
        variantName: 'Bạc Ánh Kim (Silver) - 48GB RAM / 2TB SSD',
        price: 109990000,
        originalPrice: 115000000,
        stockQuantity: 8,
        active: true,
      },
    ],
  },
};
